DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHOR;

CREATE TABLE GENRE
(
  GENRE_ID INT PRIMARY KEY,
  GENRE_NAME    VARCHAR(255) NOT NULL
);

CREATE TABLE AUTHOR
(
  AUTHOR_ID INT PRIMARY KEY,
  AUTHOR_NAME      VARCHAR(255) NOT NULL
);

CREATE TABLE BOOKS
(
  ID        INT PRIMARY KEY,
  TITLE     VARCHAR(255) NOT NULL,
  GENRE_ID  INT          NOT NULL,
  AUTHOR_ID INT          NOT NULL,
  FOREIGN KEY (GENRE_ID) references GENRE (GENRE_ID),
  FOREIGN KEY (AUTHOR_ID) references AUTHOR (AUTHOR_ID)
);
