version: '3'
services:
  library:
    container_name: library
    build: .
    ports:
      - 8080:8080
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
