spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: xpom10
    password: Passw0rd
    initialization-mode: always
  jpa:
    hibernate.ddl-auto: create-drop