spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: admin
    password: admin
    initialization-mode: always
  jpa:
    show-sql: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library
  batch:
    initialize-schema: always
  profiles:
    active: dev

