spring:
  datasource:
    url: jdbc:mysql://msk1-cbox032.unix.nspk.ru:3306/library?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: dbprof
    password: dbprof
    initialization-mode: always
  jpa:
    show-sql: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library
  batch:
    initialize-schema: always
  profiles:
    active: dev

